// Passes and serialization on the sahw dialect (docs/iree_compiler_plan.md §8.4).
#ifndef SA_TRANSFORMS_SAHWPASSES_H_
#define SA_TRANSFORMS_SAHWPASSES_H_

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "../target/Codegen.h"
#include "SahwDialect.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/Pass/Pass.h"

namespace mlir::iree_compiler::sa {

// The hardware parameters of an sa executable target (#hal.executable.target
// configuration; §8.9 item 1): the code generator reads them from here only.
struct TargetConfig {
  int64_t d = 8;
  int64_t spadBytes = 128 * 1024;    // per SPAD (two banks)
  int64_t accBytes = 256 * 1024;     // ACC (two banks)
  int64_t maxDynamic = 256;          // upper bound of a dynamic dimension
  int64_t dynFields = 2;             // dynamic fields per descriptor
  int64_t bases = 16, params = 8;    // BASE / PARAM registers (BASE15: prefixes)
  static TargetConfig fromAttr(DictionaryAttr config);
  void addTo(Builder &b, SmallVectorImpl<NamedAttribute> &attrs) const;
  CodegenOptions codegenOptions() const;
};

// C5.0: every export generated by the C3/C4 code generator (Codegen.cpp) and
// raised into a sahw.template in the variant's inner module (SahwRaise.cpp).
// C5.1: with newCodegen "on", each export first goes through the C5 pipeline
// (SahlPasses.h) and falls back to the C3/C4 generator when it fails; "only":
// no fallback; "off": the C3/C4 generator only. report: one line per export
// on stderr (which path, why not the new one).
std::unique_ptr<Pass> createSahwLegacyCodegenPass(bool allowUnsupported, const std::string &newCodegen = "off",
                                                  bool report = false);
// The body's leading loads -> sahw.head, for exports that do not touch SPAD_B.
std::unique_ptr<Pass> createSahwSplitHeadPass();
// BASE registers from 0, register-setup PARAMs from 0, private PARAMs from 7 down.
std::unique_ptr<Pass> createSahwAssignRegistersPass();
void registerSahwPasses();

// One export as sa-desc v3 wants it (SahwSerialize.cpp).
struct SerializedExport {
  std::string templ;                 // descriptors: prefix (+ RET), head (+ RET), body (+ RET)
  std::vector<SetupEntry> setup;
  uint32_t prefix = 0, prefixReads = 0, writes = 0, reads = 0, head = 0, flags = 0, prefixReg = 0;
  uint32_t cycles = 0;
};
LogicalResult serializeTemplate(sahw::TemplateOp t, SerializedExport &out);

}  // namespace mlir::iree_compiler::sa

#endif  // SA_TRANSFORMS_SAHWPASSES_H_
