#!/bin/sh
# Installs / checks / removes the accelerator pool (docs/kv260_upgrade_plan.md
# K5-M, step M1) on Ubuntu 22.04 for Kria. Run on the board with sudo, in the
# directory of accel.dtb (accel_mem_dtb.sh).
#
#   sudo sh accel_mem_install.sh install [CMA]   CMA: global CMA size, default 256M
#   (reboot)
#   sudo sh accel_mem_install.sh check
#   sudo sh accel_mem_install.sh uninstall       (then reboot)
#
# install:
#   - accel.dtb -> /boot/firmware/user-override.dtb: the Kria boot script
#     (flash-kernel's bootscr.zynqmp.kria) loads it in place of the FIT's DTB
#   - cma=<CMA> in /etc/default/flash-kernel's LINUX_KERNEL_CMDLINE, boot script
#     regenerated by flash-kernel: the script's own cma=1000M comes first, the
#     later cma= wins
#   - u-dma-buf.ko (from ~<user>/udmabuf, built for this kernel) into
#     /lib/modules/<release>/extra and loaded at boot (modules-load.d): its DT
#     node makes /dev/udmabuf0 of the pool's size, no udmabuf0= parameter
#   the originals are kept once as *.pre-accel
# Rollback without the board booting: delete user-override.dtb from the SD
# card's boot partition on a PC (the old boot script copy is boot.scr.uimg.pre-accel).
# A kernel update rebuilds image.fit but keeps user-override.dtb (the pool's
# tree is frozen at this kernel's) and needs u-dma-buf rebuilt for the new kernel.
set -eu
B=/boot/firmware
FK=/etc/default/flash-kernel
ML=/etc/modules-load.d/u-dma-buf.conf
user=${SUDO_USER:-ubuntu}
home=$(getent passwd "$user" | cut -d: -f6)
die() { echo "ERROR: $*" >&2; exit 1; }
[ "$(id -u)" = 0 ] || die "run with sudo"

case ${1:-} in
install)
    cma=${2:-256M}
    [ -f accel.dtb ] || die "accel.dtb not here (accel_mem_dtb.sh first)"
    dtc -q -I dtb -O dts accel.dtb 2>/dev/null | grep -q 'compatible = "ikwzm,u-dma-buf"' || die "accel.dtb has no u-dma-buf node"
    ko=$home/udmabuf/u-dma-buf.ko
    [ -f "$ko" ] || die "$ko missing"
    modinfo "$ko" | grep -q "vermagic: *$(uname -r) " || die "$ko is not built for $(uname -r)"
    [ -e $B/boot.scr.uimg.pre-accel ] || cp -p $B/boot.scr.uimg $B/boot.scr.uimg.pre-accel
    [ -e $FK.pre-accel ] || cp -p $FK $FK.pre-accel
    cp accel.dtb $B/user-override.dtb
    if grep -q '^LINUX_KERNEL_CMDLINE=' $FK; then
        sed -i "s/^LINUX_KERNEL_CMDLINE=.*/LINUX_KERNEL_CMDLINE=\"cma=$cma\"/" $FK
    else
        echo "LINUX_KERNEL_CMDLINE=\"cma=$cma\"" >> $FK
    fi
    flash-kernel
    strings $B/boot.scr.uimg | grep -q "cma=$cma" || die "the regenerated boot script has no cma=$cma (see $B/boot.scr.uimg)"
    install -D -m 644 "$ko" /lib/modules/"$(uname -r)"/extra/u-dma-buf.ko
    depmod -a
    echo u-dma-buf > $ML
    echo "installed: $B/user-override.dtb, cma=$cma, u-dma-buf at boot. Reboot, then: sudo sh $0 check"
    ;;
check)
    echo "== cmdline"; cat /proc/cmdline
    echo "== reserved memory"; dmesg | grep -iE "reserved mem|cma: Reserved|accel@" || true
    echo "== CMA (all areas, the pool included)"; grep -E "Cma" /proc/meminfo
    d=/sys/class/u-dma-buf/udmabuf0
    if [ -d $d ]; then
        echo "== $d: phys_addr $(cat $d/phys_addr), size $(cat $d/size) ($(( $(cat $d/size) >> 20 )) MiB), sync_mode $(cat $d/sync_mode)"
    else
        echo "== no $d (module loaded? lsmod: $(lsmod | grep -c u_dma_buf); dmesg | grep u-dma-buf:)"; dmesg | grep -i "u-dma-buf\|udmabuf" | tail -5
    fi
    ;;
uninstall)
    rm -f $B/user-override.dtb $ML
    if [ -e $FK.pre-accel ]; then cp -p $FK.pre-accel $FK; fi
    flash-kernel
    echo "removed: user-override.dtb, the cma= override, u-dma-buf at boot. Reboot (insmod u-dma-buf by hand again)."
    ;;
*)
    sed -n '2,10p' "$0"; exit 2 ;;
esac
