#!/usr/bin/env python3
"""Co-simulation cases for the descriptor-list path (firmware/sim/tb_system.v, DESC_TEST).

The lists are built by the real driver code (driver/pynq_matmul.py:
build_gemm_list / build_vector_list, DescList) with the simulated DDR
addresses, and the expected outputs come from the driver's NumPy goldens. The
testbench loads each case into its DDR model, runs desc_run_fw on PicoRV32 +
the accelerator RTL and compares the output bytes, so the Python descriptor
encoding and schedules are checked against the RTL before they reach the board.

Writes into --out: case<i>_ddr.hex (sparse, @byte-offset lines), case<i>_exp.hex
(expected output bytes) and desc_cases.vh (case count, parameters, a load task).
"""
import argparse
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "driver"))
import pynq_matmul as pm  # noqa: E402  (pynq itself is optional off the board)

DDR_BASE = 0x18000000                  # tb_system.v
A_OFF, B_OFF, C_OFF, BIAS_OFF = 0x0000, 0x4000, 0x8000, 0x10000
X_OFF, Y_OFF, O_OFF, LIST_OFF = 0x18000, 0x20000, 0x28000, 0x40000
DDR_BYTES = 0x50000


def write_sparse(path, chunks):
    """chunks: [(byte offset, bytes)] -> $readmemh file with @offset lines."""
    with open(path, "w") as f:
        for off, data in chunks:
            f.write(f"@{off:x}\n")
            f.write("\n".join(f"{b:02x}" for b in data) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--d", type=int, default=8)
    ap.add_argument("--out", default=".")
    args = ap.parse_args()
    d = args.d
    rng = np.random.default_rng(11)
    cases = []   # (name, dl, chunks, out_off, expected bytes)

    def gemm_case(name, m, n, k, bias=False, quant=None, relu=False, bsplit="auto"):
        a = rng.integers(-128, 128, (m, k), dtype=np.int8)
        b = rng.integers(-128, 128, (k, n), dtype=np.int8)
        chunks = [(A_OFF, a.tobytes()), (B_OFF, b.tobytes())]
        bias_v = None
        if bias:
            bias_v = rng.integers(-2**16, 2**16, n if quant else (m, n), dtype=np.int32)
            chunks.append((BIAS_OFF, bias_v.tobytes()))
        dl = pm.build_gemm_list(d, m, n, k, DDR_BASE + A_OFF, DDR_BASE + B_OFF, DDR_BASE + C_OFF,
                                DDR_BASE + BIAS_OFF if bias else None, quant, relu, bsplit=bsplit)
        if quant is not None:
            exp = pm.qgemm_golden(a, b, bias_v, quant, relu)
        else:
            exp = (pm.golden(a, b) + (bias_v if bias else 0)).astype(np.int32)
        cases.append((name, dl, chunks, C_OFF, exp.tobytes()))

    def vector_case(name, op, it, ot, n, ny, relu=False, requant=None):
        dt = {0: np.int8, 1: np.int16, 2: np.int32}
        info = np.iinfo(dt[it])
        x = rng.integers(info.min, info.max + 1, n, dtype=np.int64).astype(dt[it])
        y = rng.integers(info.min, info.max + 1, ny, dtype=np.int64).astype(dt[it])
        dl = pm.build_vector_list(d, op, it, ot, n, ny, DDR_BASE + X_OFF, DDR_BASE + Y_OFF,
                                  DDR_BASE + O_OFF, relu, requant)
        exp = pm.vector_golden(op, x, y, dt[ot], relu, requant)
        cases.append((name, dl, [(X_OFF, x.tobytes()), (Y_OFF, y.tobytes())], O_OFF, exp.tobytes()))

    gemm_case(f"gemm {4*d}x{4*d}x{8*d}", 4 * d, 4 * d, 8 * d)
    gemm_case(f"gemm {3*d}x{2*d}x{5*d} + bias rows", 3 * d, 2 * d, 5 * d, bias=True)
    gemm_case(f"gemm {2*d}x{8*d}x128 (B split)", 2 * d, 8 * d, 128, bsplit=True)
    gemm_case(f"int8 gemm {4*d}x{4*d}x{8*d} + bias, relu", 4 * d, 4 * d, 8 * d, bias=True,
              quant=pm.Requant(181, 15, -3), relu=True)
    vector_case("vector add i8 n=20000", "add", 0, 0, 20000, 20000)
    vector_case(f"vector add i32->i8 relu requant, bias period 8", "add", 2, 0, 4096, 8 * d, True,
                pm.Requant(300, 16, 5))
    vector_case("vector mul i16->i32 n=4112", "mul", 1, 2, 4112, 4112)

    os.makedirs(args.out, exist_ok=True)
    vh = [f"// generated by {os.path.basename(__file__)} --d {d}",
          f"localparam integer NDCASE = {len(cases)};"]
    load = ["task load_dcase(input integer c, output [31:0] n_desc, output [31:0] out_off, output [31:0] out_bytes);",
            "    case (c)"]
    for i, (name, dl, chunks, out_off, exp) in enumerate(cases):
        rows = dl.array()
        chunks = chunks + [(LIST_OFF, rows.tobytes())]
        assert all(off + len(data) <= DDR_BYTES for off, data in chunks), name
        assert O_OFF + len(exp) <= LIST_OFF or out_off == C_OFF, name
        write_sparse(os.path.join(args.out, f"case{i}_ddr.hex"), chunks)
        write_sparse(os.path.join(args.out, f"case{i}_exp.hex"), [(0, exp)])
        load.append(f'        {i}: begin $readmemh("case{i}_ddr.hex", ddr); $readmemh("case{i}_exp.hex", dexp); '
                    f'n_desc = {len(dl)}; out_off = 32\'h{out_off:x}; out_bytes = {len(exp)}; '
                    f'$display("TB   case {i}: {name}"); end')
    load += ["    endcase", "endtask"]
    with open(os.path.join(args.out, "desc_cases.vh"), "w") as f:
        f.write("\n".join(vh + load) + "\n")
    print(f"{len(cases)} cases for D = {d} in {args.out}")


if __name__ == "__main__":
    main()
