#!/usr/bin/env python3
"""Writes sa_sfu_tables.vh: the SFU table ROM of the L2 vector engine, from
llm/sfu.py tables() (so the RTL and the bit-exact model use the same
values). Entry = {T, S} (64 bits); address {fn, index}: fn 0 EXP (64
entries), 1 RECIP (64), 2 RSQRT (128: odd exponent * 64 + index).

    python3 gen_sfu_tables.py      (from rtl/sysarray; needs NumPy)"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "llm"))
import sfu  # noqa: E402

t = sfu.tables()
lines = ["// generated by gen_sfu_tables.py from llm/sfu.py -- do not edit",
         "// {T, S} of the SFU segment tables: a = {fn[1:0], idx[6:0]} (fn 0 EXP, 1 RECIP, 2 RSQRT)",
         "function [63:0] sfu_rom(input [8:0] a);",
         "    case (a)"]
for fn, name in enumerate(("exp", "recip", "rsqrt")):
    T, S = t[name]
    for i in range(len(T)):
        lines.append(f"        9'h{fn << 7 | i:03x}: sfu_rom = 64'h{int(T[i]):08x}_{int(S[i]):08x};")
lines += ["        default: sfu_rom = 64'd0;", "    endcase", "endfunction"]
open(os.path.join(HERE, "sa_sfu_tables.vh"), "w").write("\n".join(lines) + "\n")
print(f"sa_sfu_tables.vh: {sum(len(v[0]) for v in t.values())} entries")
